# SPDX-FileCopyrightText: 2010 - 2024 the Friendica project
#
# SPDX-License-Identifier: CC0-1.0

codecov:
  branch: develop
  ci:
    - ci.friendi.ca

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment: false
