# SPDX-FileCopyrightText: 2010 - 2024 the Friendica project
#
# SPDX-License-Identifier: CC0-1.0

steps:
  build_xgettext:
    image: friendicaci/transifex
    commands:
      - ./bin/run_xgettext.sh
  check:
    image: friendicaci/transifex
    commands:
      - /check-messages.sh

when:
  - branch:
      exclude: [ stable ]
